M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-10-08T02:21:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-08T02:21:29+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X132.703Y-130.201
X138.483Y-130.201
M30
